// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateEntry(arg1:string,arg2:string):Promise<models.Entry>;

export function CreateTodo(arg1:string):Promise<models.Todo>;

export function DeleteEntry(arg1:string):Promise<void>;

export function DeleteTodo(arg1:string):Promise<void>;

export function GetEntries():Promise<Array<models.Entry>>;

export function GetTodos():Promise<Array<models.Todo>>;

export function UpdateTodoStatus(arg1:string,arg2:string):Promise<void>;
