// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEntry(arg1, arg2) {
  return window['go']['main']['App']['CreateEntry'](arg1, arg2);
}

export function CreateTodo(arg1) {
  return window['go']['main']['App']['CreateTodo'](arg1);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function GetEntries() {
  return window['go']['main']['App']['GetEntries']();
}

export function GetTodos() {
  return window['go']['main']['App']['GetTodos']();
}

export function UpdateTodoStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateTodoStatus'](arg1, arg2);
}
