name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "black==24.3.0" "ruff==0.14.1" "isort==5.12.0" "mypy==1.7.0" "pytest==8.4.3"
          pip install -e .
      - name: Run black (check)
        run: black --check .
      - name: Run ruff
        run: ruff .
      - name: Run isort (check)
        run: isort --check-only .
      - name: Type check
        run: mypy .
      - name: Run tests
        run: pytest -q